serverUrl: http://mywebsite.com
shortTitle: IntelliFactory Blog
title: IntelliFactory
description: Building business applications with F# since 2004
masterUserDisplayName: IntelliFactory
masterLanguage: en
languages: "en->English,es->Spanish,hu->Hungarian"
users: "granicz->Adam Granicz"