name: Update submodules
on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
        submodules: true
      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add .
          git config --local user.email "ci@intellifactory.com
          git config --local user.name "IntelliFactory CI"
          git commit -m "Update submodules"
          git push

      
